# Generated by Django 3.2.20 on 2023-07-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='Quanteda',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='purchase_value',
            new_name='Valor',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='color',
            new_name='cor',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='model',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='size',
            new_name='tam',
        ),
    ]
