# Generated by Django 3.2.20 on 2023-07-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230721_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Quanteda',
            new_name='quantidade',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Valor',
            new_name='valor',
        ),
    ]
