# Generated by Django 3.2.20 on 2023-07-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_tam_item_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
